### ISSUE TITLE
Asterisks in recipe lists are not wrapped as strings

### ISSUE THREAD

**Issue by jtymes** [openrewrite/rewrite-recipe-markdown-generator#165]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v6.1.3

The recipe list for something like the [Spring Boot 3.3 upgrade](https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_3) has sections like this:

```yaml
recipeList:
  - org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
  - org.openrewrite.java.spring.boot3.SpringBootProperties_3_3
  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:
      groupId: org.springframework.boot
      artifactId: *
      newVersion: 3.3.x
      overrideManagedVersion: false
```

The `artifactId` is a `*`. When copying this YAML into a custom recipe, the Maven plugin fails:

```shell
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:6.1.3:run (default-cli) on project asterisk: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:6.1.3:run failed: while scanning an alias
[ERROR]  in 'reader', line 14, column 19:
[ERROR]           artifactId: *
[ERROR]                       ^
[ERROR] unexpected character found
[ERROR] (10)
[ERROR]  in 'reader', line 14, column 20:
[ERROR]           artifactId: *
[ERROR]                        ^
[ERROR]
[ERROR] -> [Help 1]
```

The [source of the recipe](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot-33.yml) has the asterisk wrapped as a string. 

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, I can open a PR. The proposed fix would be to handle the asterisk as a special case inside `RecipeDescriptorExtension.kt`:

```kotlin
val formattedValue = if (value is Array<*>) {
        val asArray =  value as Array<*>
        "[${asArray.joinToString(", ")}]"
    } else if (value == "*") {
        "\"*\""
    } else {
        value
    }
```

This produces the expected output:

```yaml
recipeList:
  - org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
  - org.openrewrite.java.spring.boot3.SpringBootProperties_3_3
  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:
      groupId: org.springframework.boot
      artifactId: "*"
      newVersion: 3.3.x
      overrideManagedVersion: false
```
